sudo: required

language: oraclejdk8

services:
  - docker

before_install:
  - docker run bpetri/cagent_builder build_script > cagent_builder.sh && chmod +x cagent_builder.sh 

install:
  - ./cagent_builder.sh make_bundles

deploy:
  provider: bintray
  file: $TRAVIS_BUILD_DIR/deployment.json
  user: bpetri
  key: $BINTRAY_KEY
